apiVersion: v1
kind: Service
metadata:
  name: "temporal-matching-server"
  labels:
{{ include "temporal-matching-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.ip }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "temporal-matching-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}