apiVersion: v1
entries:
  temporal-matching:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-02T00:09:19.635802291Z"
    description: A Helm chart for Kubernetes
    digest: e6f17e657920697bd598d8460060e45c5ec33e18f7b30bcc74d5950758cd2c87
    name: temporal-matching
    urls:
    - charts/temporal-matching-1.0.1.tgz
    version: 1.0.1
  temporal-matching-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-02T00:09:19.62855695Z"
    description: A Helm chart for Kubernetes
    digest: b1d69de5839b98be0c36b89e7c9e8755fcb0b85bdbacc0c93d95329c277eeee0
    name: temporal-matching-frontend
    urls:
    - charts/temporal-matching-frontend-1.0.1.tgz
    version: 1.0.1
  temporal-matching-server:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-02T00:09:19.619521489Z"
    description: A Helm chart for Kubernetes
    digest: 66f8e0141a35e4e7210b8c6943059ea205e370c7b80393a2f290d12d6c0c9b6c
    name: temporal-matching-server
    urls:
    - charts/temporal-matching-server-1.0.1.tgz
    version: 1.0.1
generated: "2021-03-02T00:09:20Z"
serverInfo: {}
